[package]
name = "hi"
version = "0.1.0"
authors = ["heroes-coding <jeremy@heroes.report>"]
license = "MIT"
build = "build.rs"

[lib]
name = "hi"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
